=== Vaidikk/XmlTut/XmlXsdTest/src/movies.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.riptide.com/movies" 
xmlns:rip="http://www.riptide.com/movies" elementFormDefault="qualified">

	<element name="movies">
		<complexType>
			<sequence>
				<element name="movie" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="code">
								<simpleType>
									<restriction base="int">
										<totalDigits value="4"/>
										<minInclusive value="5001"/>
										<maxExclusive value="6000"/>
									</restriction>
								</simpleType>
							</element>
							<element name="title" type="string"/>
							<element name="release-date" type="date" minOccurs="0"/>
							<element name="theater-name" maxOccurs="unbounded">
								<simpleType>
									<restriction base="string">
										<minLength value="4"/>
										<maxLength value="20"/>
									</restriction>	
								</simpleType>
							</element>
							<element name="city" type="string" minOccurs="0" maxOccurs="unbounded"/>
						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== Vaidikk/XmlTut/XmlXsdTest/src/moviedetails.xml
<?xml version="1.0" encoding="UTF-8"?>
<rip:movies xmlns:rip="http://www.riptide.com/movies" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.riptide.com/movies movies.xsd ">
  <rip:movie>
    <rip:code>5001</rip:code>
    <rip:title>Southpaw</rip:title>
    <rip:theater-name>Cinepolis</rip:theater-name>
  </rip:movie>
  <rip:movie>
  	<rip:code>5002</rip:code>
  	<rip:title>Warrior</rip:title>
  	<rip:theater-name>Broadway</rip:theater-name>
  </rip:movie>
</rip:movies>
